### PR TITLE
Complex string identification and subroutine tweaks

### PR DESCRIPTION
**Pull request by jordonbrill**
Enhancements since jacobbennett's initial version of this syntax for sublime: https://github.com/jordonbrill/sublime-pickbasic

Modified to not change enhancements you have already made.

Properly highlight `SUBROUTINE` calls
Properly highlight control-break logic calls
Identify GOSUB lines better
Cleanup the calling of a subroutine using the `CALL` keyword
Significantly improve the process of identifying strings or quoted characters

### CODE REVIEW

**Comment by itsxallwater** [comment]
I'll try and grab these to review tomorrow. Love seeing more contributions here!

**Review by itsxallwater — CHANGES_REQUESTED** [review]
I would update your SUBROUTINE, CALL and GOSUB matches to also include a-z like so:

`<string>(SUBROUTINE)\s+([a-zA-Z0-9_-]+)</string>`

I like the concept of highlighting the target's name but defer to Travis on this. I'd also suggest adding a handler for GOTO so that it behaves the same way. Other than that, so far this looks good!

I just want to reiterate my excitement over seeing other activity here. I was just talking with a colleague of mine yesterday about how we need to champion work on projects like this so your timing couldn't have been better.

**Comment by jordonbrill** [comment]
I'm super excited to find others out there trying to work with PICK in a somewhat modern way! I'll try to push changes later today.

**Comment by jordonbrill** [comment]
Do you have any other requested changes?

**Review by itsxallwater — APPROVED** [review]
I think these look good!

**Comment by jordonbrill** [comment]
Can this get merged in and deployed so VS Code can use the latest release?

**Comment by itsxallwater** [comment]
Tagging @mallek, when you get a chance to review

**Comment by mallek** [comment]
Sorry I am out of town this week.  I'll try to look at it this evening and get it pushed to vscode marketplace

**Comment by mallek** [comment]
Looked it over, great work.  Thanks @itsxallwater for the review your comments were spot on.  I am pushing it to the extension marketplace now

**Comment by mallek** [comment]
I updated the extension in the marketplace and you should be able to update.  Thanks again @jordonbrill

**Pull request merged**
